"use client";

import { memo, type ReactNode } from "react";
import {
  BriefcaseBusiness,
  CheckSquare,
  Download,
  FileText,
  Loader2,
  TrendingDown,
  TrendingUp,
} from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { EASE_OUT_EXPO, motionDuration, staggerDelay } from "@/components/motion/variants";
import { cx } from "@/components/ui";
import { averageReliability, toneClasses, topInfluenceAgent } from "@/lib/council";
import { fmtMonths, fmtSignedMonths } from "@/lib/format";
import type {
  BoardMemo as StructuredBoardMemo,
  DebateState,
  OperatorAction,
  ReliabilityScore,
  RunwayImpact,
} from "@/lib/types";
import { CfoRulingCard } from "./cfo-ruling";
import { CopyButton, EmptyState, Panel, SectionLabel, SkeletonText } from "./primitives";

function buildBoardMemo(
  decision: string | undefined,
  rec: NonNullable<DebateState["recommendation"]>,
  companyName: string,
  boardMemo?: StructuredBoardMemo,
  operatorActions?: OperatorAction[],
  avgReliability?: number,
): string {
  const lines: string[] = [];
  lines.push(`# Board Memo — ${companyName}`);
  lines.push("");
  if (boardMemo?.headline) {
    lines.push(`**Headline:** ${boardMemo.headline}`);
    lines.push("");
  }
  lines.push(`**Decision under review:** ${decision || "—"}`);
  lines.push("");
  const confidenceSuffix = typeof rec.confidence === "number" ? ` (${rec.confidence}% confidence)` : "";
  if (rec.is_verdict === false) {
    // Open-ended / multiple-choice: lead with the human headline under the
    // adaptive label, not the raw RECOMMENDATION / SELECTION token.
    const answerLabel = rec.answer_label || "Recommendation";
    const answerBody = rec.headline?.trim() || rec.decision || "—";
    lines.push(`**${answerLabel}:** ${answerBody}${confidenceSuffix}`);
  } else {
    lines.push(`**Recommendation:** ${rec.decision ?? "—"}${confidenceSuffix}`);
  }
  if (rec.is_verdict === false && rec.recommended_actions?.length) {
    lines.push("");
    lines.push("## Recommended course of action");
    rec.recommended_actions.forEach((action, index) => lines.push(`${index + 1}. ${action}`));
  }
  if (rec.is_verdict === false && rec.selected_options?.length) {
    lines.push("");
    lines.push("## Selected option(s)");
    for (const option of rec.selected_options) lines.push(`- ${option}`);
  }
  if (rec.ruling) {
    lines.push("");
    lines.push(`**CFO ruling:** ${rec.ruling}`);
  }
  if (rec.rationale) {
    lines.push("");
    lines.push(rec.rationale);
  }
  const impact = rec.impact;
  if (impact && typeof impact.scenario_runway_months === "number") {
    lines.push("");
    lines.push("## Runway impact");
    lines.push(`- Current runway: ${fmtMonths(impact.current_runway_months)}`);
    lines.push(`- After this decision: ${fmtMonths(impact.scenario_runway_months)}`);
    lines.push(`- Net impact: ${fmtSignedMonths(impact.delta_months)}`);
    if (impact.note) lines.push(`- Note: ${impact.note}`);
  }
  if (rec.runway_impact_summary) {
    lines.push("");
    lines.push(`**Runway summary:** ${rec.runway_impact_summary}`);
  }
  if (boardMemo?.key_figures?.length) {
    lines.push("");
    lines.push("## Key figures");
    for (const figure of boardMemo.key_figures) lines.push(`- ${figure}`);
  }
  if (rec.tradeoffs?.length) {
    lines.push("");
    lines.push("## Tradeoffs weighed");
    for (const tradeoff of rec.tradeoffs) lines.push(`- ${tradeoff}`);
  }
  if (rec.key_risks?.length) {
    lines.push("");
    lines.push("## Key risks");
    for (const risk of rec.key_risks) lines.push(`- ${risk}`);
  }
  if (rec.conditions?.length) {
    lines.push("");
    lines.push("## Conditions");
    for (const condition of rec.conditions) lines.push(`- ${condition}`);
  }
  if (rec.assumptions_converted_to_conditions?.length) {
    lines.push("");
    lines.push("## Assumptions converted to conditions");
    for (const condition of rec.assumptions_converted_to_conditions) lines.push(`- ${condition}`);
  }
  if (rec.dissent) {
    lines.push("");
    lines.push("## Dissent resolved");
    lines.push(rec.dissent);
  }
  const actions = operatorActions?.length ? operatorActions : boardMemo?.operator_actions;
  if (actions?.length) {
    lines.push("");
    lines.push("## Operator actions");
    for (const action of actions) {
      const meta = [action.owner, action.due, action.priority].filter(Boolean).join("; ");
      lines.push(`- ${action.action}${meta ? ` (${meta})` : ""}`);
    }
  }
  const influence = rec.council_influence;
  if (influence?.weights?.length) {
    lines.push("");
    lines.push("## Council influence");
    for (const weight of influence.weights) {
      lines.push(`- ${weight.agent_id}: ${weight.influence_weight}%`);
    }
    if (influence.summary) lines.push(`- Summary: ${influence.summary}`);
  }
  lines.push("");
  if (typeof avgReliability === "number") lines.push(`Council reliability: ${avgReliability}%`);
  lines.push("Generated by the Atlas AI Council.");
  return lines.join("\n");
}

function downloadMemo(memo: string, companyName: string) {
  if (typeof document === "undefined") return;
  const blob = new Blob([memo], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `atlas-board-memo-${companyName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export const BoardMemo = memo(BoardMemoBase);

function BoardMemoBase({
  boardMemo,
  recommendation,
  decision,
  companyName,
  reliabilityScores,
  operatorActions,
  running,
  healthReady,
  started,
}: {
  boardMemo?: StructuredBoardMemo;
  recommendation?: DebateState["recommendation"];
  decision?: string;
  companyName: string;
  reliabilityScores: ReliabilityScore[];
  operatorActions?: OperatorAction[];
  running: boolean;
  healthReady: boolean;
  started: boolean;
}) {
  const reduced = useReducedMotion();
  const shouldReduce = reduced ?? false;
  const rec = recommendation;
  const hasDecision = Boolean(rec?.decision);
  // Open-ended / multiple-choice answers are not "rulings" — soften the chrome copy.
  const nonVerdict = rec?.is_verdict === false;
  const panelTitle = nonVerdict ? "CFO recommendation" : "CFO ruling";
  const packetHeadline = boardMemo?.headline ?? (nonVerdict ? "Board-ready CFO recommendation issued" : "Board-ready CFO ruling issued");
  const avg = averageReliability(reliabilityScores);
  const leadInfluence = topInfluenceAgent(rec?.council_influence);
  const memo = hasDecision && rec ? buildBoardMemo(decision, rec, companyName, boardMemo, operatorActions, avg) : "";
  const actions = operatorActions?.length ? operatorActions : boardMemo?.operator_actions ?? [];
  const keyFigures = getKeyFigures(boardMemo, rec);
  const memoConditions = rec?.conditions?.length ? rec.conditions : boardMemo?.conditions ?? [];
  const memoDissent = rec?.dissent ?? boardMemo?.dissent;
  const reveal = (index: number) => (shouldReduce ? 0 : index * 0.055);

  return (
    <Panel
      id="council-memo"
      visualIcon="memo"
      title={panelTitle}
      action={
        hasDecision ? (
          <div className="flex items-center gap-1.5">
            <CopyButton text={memo} label="Copy" />
            <button
              type="button"
              onClick={() => downloadMemo(memo, companyName)}
              className="inline-flex h-7 shrink-0 items-center justify-center gap-1.5 rounded-md border border-border bg-surface px-2 text-[11px] font-semibold text-muted-foreground transition-colors hover:bg-surface-muted hover:text-foreground"
            >
              <Download className="h-3.5 w-3.5" strokeWidth={2} />
              Export
            </button>
          </div>
        ) : undefined
      }
    >
      {hasDecision && rec ? (
        <motion.div
          className="relative"
          data-board-memo-artifact="true"
          initial={shouldReduce ? false : "hidden"}
          animate="show"
          variants={{ hidden: {}, show: { transition: { staggerChildren: 0.055 } } }}
        >
          <MemoStage delay={reveal(0)} reduced={shouldReduce}>
            <div className="mb-3 rounded-lg border border-border bg-background p-3">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="font-mono text-[9px] font-semibold uppercase tracking-[0.18em] text-subtle-foreground">
                    Executive packet
                  </div>
                  <h3 className="mt-1 font-display text-[18px] font-medium leading-tight text-foreground">
                    {packetHeadline}
                  </h3>
                  {boardMemo?.context && (
                    <p className="mt-1 max-w-2xl break-words text-[12px] leading-relaxed text-muted-foreground">
                      {boardMemo.context}
                    </p>
                  )}
                </div>
                <div className="flex shrink-0 items-center gap-2 rounded-md border border-border bg-surface px-2.5 py-1.5 text-[11px] font-semibold text-muted-foreground">
                  <FileText className="h-3.5 w-3.5 text-accent" strokeWidth={2.25} />
                  Board artifact
                </div>
              </div>
            </div>
          </MemoStage>

          <MemoStage delay={reveal(1)} reduced={shouldReduce}>
            <CfoRulingCard
              decision={rec.decision!}
              confidence={rec.confidence}
              ruling={rec.ruling}
              rationale={rec.rationale}
              tradeoffs={rec.tradeoffs}
              analystInfluence={rec.analyst_influence}
              conditions={memoConditions}
              dissent={memoDissent}
              runwayImpactSummary={rec.runway_impact_summary}
              operatorActions={actions}
              questionKind={rec.question_kind}
              isVerdict={rec.is_verdict}
              headline={rec.headline}
              answerLabel={rec.answer_label}
              recommendedActions={rec.recommended_actions}
              selectedOptions={rec.selected_options}
              variant="memo"
            />
          </MemoStage>

          <MemoStage delay={reveal(2)} reduced={shouldReduce} className="mt-3 flex flex-wrap gap-2">
            {leadInfluence && (
              <span className="rounded-md border border-border bg-background px-2.5 py-1 text-[11px] font-semibold tabular-nums text-muted-foreground">
                {leadInfluence.agent_id} led at {leadInfluence.influence_weight}% influence
              </span>
            )}
            {typeof rec.confidence_factors?.delta === "number" && rec.confidence_factors.delta !== 0 && (
              <span className="rounded-md border border-border bg-background px-2.5 py-1 text-[11px] font-semibold tabular-nums text-muted-foreground">
                Confidence {rec.confidence_factors.delta > 0 ? "+" : ""}
                {rec.confidence_factors.delta} from council cohesion
              </span>
            )}
            {typeof avg === "number" && (
              <span className="rounded-md border border-border bg-background px-2.5 py-1 text-[11px] font-semibold tabular-nums text-muted-foreground">
                Council reliability {avg}%
              </span>
            )}
          </MemoStage>

          {keyFigures.length > 0 && (
            <MemoStage delay={reveal(3)} reduced={shouldReduce}>
              <KeyFigureStrip figures={keyFigures} />
            </MemoStage>
          )}

          {(rec.key_risks?.length || memoConditions.length || memoDissent) && (
            <MemoStage delay={reveal(4)} reduced={shouldReduce} className="mt-3 grid gap-3 sm:grid-cols-2">
              {rec.key_risks && rec.key_risks.length > 0 && (
                <MemoList title="Key risks" items={rec.key_risks} dotTone="risk" />
              )}
              {memoConditions.length > 0 && (
                <MemoList title="Conditions" items={memoConditions} dotTone="info" />
              )}
              {memoDissent && (
                <MemoList title="Dissent resolved" items={[memoDissent]} dotTone="risk" />
              )}
            </MemoStage>
          )}

          {actions.length > 0 && (
            <MemoStage delay={reveal(5)} reduced={shouldReduce}>
              <OperatorActionsList actions={actions} />
            </MemoStage>
          )}
        </motion.div>
      ) : running ? (
        <div>
          <div className="mb-2 flex items-center gap-2 text-[12px] font-semibold text-info">
            <Loader2 className="h-3.5 w-3.5 animate-spin" strokeWidth={2.25} />
            The CFO will rule once cross-examination completes.
          </div>
          <SkeletonText lines={3} />
        </div>
      ) : (
        <EmptyState visualIcon={healthReady ? "memo" : "health"}>
          {!healthReady
            ? "Preflight must pass before the CFO can issue a ruling."
            : started
              ? "Awaiting the CFO's board-ready ruling."
              : "Submit a decision — the CFO's ruling, risks, and conditions land here."}
        </EmptyState>
      )}
    </Panel>
  );
}

function getKeyFigures(boardMemo?: StructuredBoardMemo, rec?: DebateState["recommendation"]): string[] {
  if (boardMemo?.key_figures?.length) return boardMemo.key_figures;
  const figures: string[] = [];
  const impact = rec?.impact;
  if (typeof impact?.current_runway_months === "number") figures.push(`Current runway: ${fmtMonths(impact.current_runway_months)}`);
  if (typeof impact?.scenario_runway_months === "number") figures.push(`Post-decision runway: ${fmtMonths(impact.scenario_runway_months)}`);
  if (typeof impact?.delta_months === "number") figures.push(`Runway delta: ${fmtSignedMonths(impact.delta_months)}`);
  if (typeof rec?.confidence === "number") figures.push(`CFO confidence: ${rec.confidence}%`);
  return figures;
}

function MemoStage({
  children,
  delay,
  reduced,
  className,
}: {
  children: ReactNode;
  delay: number;
  reduced: boolean;
  className?: string;
}) {
  return (
    <motion.div
      className={className}
      initial={reduced ? false : { opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: motionDuration.reveal, delay, ease: EASE_OUT_EXPO }}
    >
      {children}
    </motion.div>
  );
}

function KeyFigureStrip({ figures }: { figures: string[] }) {
  const reduced = Boolean(useReducedMotion());
  return (
    <div className="mt-3 rounded-lg border border-border bg-background p-2.5">
      <div className="mb-2 flex items-center gap-1.5">
        <BriefcaseBusiness className="h-3.5 w-3.5 text-accent" strokeWidth={2.25} />
        <SectionLabel>Key figures</SectionLabel>
      </div>
      <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
        {figures.slice(0, 4).map((figure, index) => {
          const [label, ...valueParts] = figure.split(":");
          const value = valueParts.join(":").trim();
          return (
            <motion.div
              key={`${figure}-${index}`}
              className="min-w-0 rounded-md border border-border bg-surface px-2.5 py-2"
              initial={reduced ? false : { opacity: 0, y: 8 }}
              animate={reduced ? { opacity: 1 } : { opacity: 1, y: 0 }}
              transition={{ duration: motionDuration.normal, delay: staggerDelay(index, 0.035, 0.16), ease: EASE_OUT_EXPO }}
            >
              <div className="truncate text-[10px] font-semibold uppercase text-subtle-foreground">{label.trim()}</div>
              <div className="mt-1 break-words text-[13px] font-semibold tabular-nums text-foreground">
                {value || figure}
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}

function OperatorActionsList({ actions }: { actions: OperatorAction[] }) {
  const reduced = Boolean(useReducedMotion());
  return (
    <div className="mt-3 rounded-lg border border-border bg-background p-2.5">
      <div className="mb-2 flex items-center justify-between gap-2">
        <div className="flex items-center gap-1.5">
          <CheckSquare className="h-3.5 w-3.5 text-accent" strokeWidth={2.25} />
          <SectionLabel>Operator actions</SectionLabel>
        </div>
        <span className="rounded-full border border-border bg-surface px-2 py-0.5 text-[10px] font-semibold tabular-nums text-muted-foreground">
          {actions.length}
        </span>
      </div>
      <ol className="grid gap-2 sm:grid-cols-2">
        {actions.slice(0, 6).map((action, index) => (
          <motion.li
            key={`${action.action}-${index}`}
            className="rounded-md border border-border bg-surface px-2.5 py-2"
            initial={reduced ? false : { opacity: 0, y: 8 }}
            animate={reduced ? { opacity: 1 } : { opacity: 1, y: 0 }}
            transition={{ duration: motionDuration.normal, delay: staggerDelay(index, 0.035, 0.16), ease: EASE_OUT_EXPO }}
          >
            <div className="flex items-start gap-2">
              <span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full border border-border bg-background text-[10px] font-semibold tabular-nums text-muted-foreground">
                {index + 1}
              </span>
              <div className="min-w-0">
                <p className="break-words text-[12px] font-semibold leading-relaxed text-foreground">{action.action}</p>
                {(action.owner || action.due || action.priority || action.depends_on) && (
                  <p className="mt-0.5 break-words text-[10.5px] font-medium text-muted-foreground">
                    {[action.owner, action.due, action.priority, action.depends_on && `depends on ${action.depends_on}`]
                      .filter(Boolean)
                      .join(" · ")}
                  </p>
                )}
              </div>
            </div>
          </motion.li>
        ))}
      </ol>
    </div>
  );
}

function MemoList({ title, items, dotTone }: { title: string; items: string[]; dotTone: "risk" | "info" }) {
  return (
    <div className="rounded-md border border-border bg-background p-2.5">
      <SectionLabel>{title}</SectionLabel>
      <ul className="mt-2 space-y-1.5">
        {items.map((item) => (
          <li key={item} className="flex gap-1.5 text-[12px] leading-relaxed text-muted-foreground">
            <span className={cx("mt-1.5 h-1 w-1 shrink-0 rounded-full", toneClasses(dotTone).dot)} />
            <span className="break-words">{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// --------------------------------------------------------------------------- //
// Scenario impact — computed runway today vs after the decision.
// --------------------------------------------------------------------------- //
export function ScenarioImpactCard({ impact }: { impact?: RunwayImpact }) {
  const hasScenario = impact && typeof impact.scenario_runway_months === "number";
  const delta = impact?.delta_months ?? null;
  const deltaTone = delta == null ? "neutral" : delta < 0 ? "risk" : delta > 0 ? "positive" : "neutral";

  return (
    <Panel icon={delta != null && delta < 0 ? TrendingDown : TrendingUp} visualIcon="runway" title="Runway impact">
      {hasScenario ? (
        <>
          <div className="grid gap-2 [grid-template-columns:repeat(3,minmax(0,1fr))]">
            <ImpactTile label="Runway today" value={fmtMonths(impact?.current_runway_months)} />
            <ImpactTile label="After decision" value={fmtMonths(impact?.scenario_runway_months)} />
            <ImpactTile label="Net impact" value={fmtSignedMonths(delta)} tone={deltaTone} />
          </div>
          {impact?.note && <p className="mt-2.5 break-words text-[11px] leading-relaxed text-muted-foreground">{impact.note}</p>}
        </>
      ) : (
        <EmptyState visualIcon="runway">Runway delta is computed from the company cash record after the CFO rules.</EmptyState>
      )}
    </Panel>
  );
}

function ImpactTile({ label, value, tone }: { label: string; value: string; tone?: "risk" | "positive" | "neutral" }) {
  const cls = tone === "risk" ? "text-risk" : tone === "positive" ? "text-positive" : "text-foreground";
  return (
    <div className="rounded-md border border-border bg-background px-2 py-2 text-center">
      <div className="text-[10px] text-subtle-foreground">{label}</div>
      <div className={cx("mt-1 text-[18px] font-semibold leading-none tabular-nums", cls)}>{value}</div>
    </div>
  );
}
