"use client";

import { Download, Gavel, Loader2, TrendingDown, TrendingUp } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import { springSnappy } from "@/components/motion/variants";
import { cx } from "@/components/ui";
import { averageReliability, decisionTone, topInfluenceAgent, toneClasses } from "@/lib/council";
import { fmtMonths, fmtSignedMonths } from "@/lib/format";
import type { DebateState, ReliabilityScore, RunwayImpact } from "@/lib/types";
import { CopyButton, EmptyState, Panel, SectionLabel, SkeletonText } from "./primitives";

function buildBoardMemo(
  decision: string | undefined,
  rec: NonNullable<DebateState["recommendation"]>,
  companyName: string,
  avgReliability?: number,
): string {
  const lines: string[] = [];
  lines.push(`# Board Memo — ${companyName}`);
  lines.push("");
  lines.push(`**Decision under review:** ${decision || "—"}`);
  lines.push("");
  lines.push(`**Recommendation:** ${rec.decision ?? "—"}${typeof rec.confidence === "number" ? ` (${rec.confidence}% confidence)` : ""}`);
  if (rec.rationale) {
    lines.push("");
    lines.push(rec.rationale);
  }
  const impact = rec.impact;
  if (impact && typeof impact.scenario_runway_months === "number") {
    lines.push("");
    lines.push("## Runway impact");
    lines.push(`- Current runway: ${fmtMonths(impact.current_runway_months)}`);
    lines.push(`- After this decision: ${fmtMonths(impact.scenario_runway_months)}`);
    lines.push(`- Net impact: ${fmtSignedMonths(impact.delta_months)}`);
    if (impact.note) lines.push(`- Note: ${impact.note}`);
  }
  if (rec.key_risks?.length) {
    lines.push("");
    lines.push("## Key risks");
    for (const risk of rec.key_risks) lines.push(`- ${risk}`);
  }
  if (rec.conditions?.length) {
    lines.push("");
    lines.push("## Conditions");
    for (const condition of rec.conditions) lines.push(`- ${condition}`);
  }
  const influence = rec.council_influence;
  if (influence?.weights?.length) {
    lines.push("");
    lines.push("## Council influence");
    for (const weight of influence.weights) {
      lines.push(`- ${weight.agent_id}: ${weight.influence_weight}%`);
    }
    if (influence.summary) lines.push(`- Summary: ${influence.summary}`);
  }
  lines.push("");
  if (typeof avgReliability === "number") lines.push(`Council reliability: ${avgReliability}%`);
  lines.push("Generated by the Atlas AI Council.");
  return lines.join("\n");
}

function downloadMemo(memo: string, companyName: string) {
  if (typeof document === "undefined") return;
  const blob = new Blob([memo], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `atlas-board-memo-${companyName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.md`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function BoardMemo({
  recommendation,
  decision,
  companyName,
  reliabilityScores,
  running,
  healthReady,
  started,
}: {
  recommendation?: DebateState["recommendation"];
  decision?: string;
  companyName: string;
  reliabilityScores: ReliabilityScore[];
  running: boolean;
  healthReady: boolean;
  started: boolean;
}) {
  const reduced = useReducedMotion();
  const rec = recommendation;
  const hasDecision = Boolean(rec?.decision);
  const avg = averageReliability(reliabilityScores);
  const leadInfluence = topInfluenceAgent(rec?.council_influence);
  const tone = hasDecision ? toneClasses(decisionTone(rec?.decision)) : null;
  const memo = hasDecision && rec ? buildBoardMemo(decision, rec, companyName, avg) : "";

  return (
    <Panel
      id="council-memo"
      icon={Gavel}
      visualIcon="memo"
      title="Recommendation"
      action={
        hasDecision ? (
          <div className="flex items-center gap-1.5">
            <CopyButton text={memo} label="Copy" />
            <button
              type="button"
              onClick={() => downloadMemo(memo, companyName)}
              className="inline-flex h-7 shrink-0 items-center justify-center gap-1.5 rounded-md border border-border bg-surface px-2 text-[11px] font-semibold text-muted-foreground transition-colors hover:bg-surface-muted hover:text-foreground"
            >
              <Download className="h-3.5 w-3.5" strokeWidth={2} />
              Export
            </button>
          </div>
        ) : undefined
      }
    >
      {hasDecision && rec ? (
        <motion.div
          initial={reduced ? false : { opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
        >
          <div className="flex flex-wrap items-center gap-2">
            <motion.span
              className={cx("inline-flex items-center gap-1.5 rounded-md border px-3 py-1 text-[15px] font-bold", tone?.soft)}
              initial={reduced ? false : { scale: 0.92, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={springSnappy}
            >
              <Gavel className="h-4 w-4" strokeWidth={2.25} />
              {rec.decision}
            </motion.span>
            {typeof rec.confidence === "number" && (
              <span className="rounded-md border border-border bg-background px-2.5 py-1 text-[12px] font-semibold tabular-nums text-muted-foreground">
                {rec.confidence}% confidence
              </span>
            )}
            {leadInfluence && (
              <span className="rounded-md border border-border bg-background px-2.5 py-1 text-[12px] font-semibold tabular-nums text-muted-foreground">
                {leadInfluence.agent_id} {leadInfluence.influence_weight}% influence
              </span>
            )}
            {typeof rec.confidence_factors?.delta === "number" && rec.confidence_factors.delta !== 0 && (
              <span className="rounded-md border border-border bg-background px-2.5 py-1 text-[12px] font-semibold tabular-nums text-muted-foreground">
                Confidence {rec.confidence_factors.delta > 0 ? "+" : ""}
                {rec.confidence_factors.delta} from council cohesion
              </span>
            )}
            {typeof avg === "number" && (
              <span className="rounded-md border border-border bg-background px-2.5 py-1 text-[12px] font-semibold tabular-nums text-muted-foreground">
                Reliability {avg}%
              </span>
            )}
          </div>

          {rec.rationale && (
            <p className="dropcap mt-3 break-words font-serif text-[14px] leading-relaxed text-foreground">{rec.rationale}</p>
          )}

          {(rec.key_risks?.length || rec.conditions?.length) && (
            <div className="mt-3 grid gap-3 sm:grid-cols-2">
              {rec.key_risks && rec.key_risks.length > 0 && (
                <MemoList title="Key risks" items={rec.key_risks} dotTone="risk" />
              )}
              {rec.conditions && rec.conditions.length > 0 && (
                <MemoList title="Conditions" items={rec.conditions} dotTone="info" />
              )}
            </div>
          )}
        </motion.div>
      ) : running ? (
        <div>
          <div className="mb-2 flex items-center gap-2 text-[12px] font-semibold text-info">
            <Loader2 className="h-3.5 w-3.5 animate-spin" strokeWidth={2.25} />
            The CFO will rule once cross-examination completes.
          </div>
          <SkeletonText lines={3} />
        </div>
      ) : (
        <EmptyState icon={Gavel} visualIcon={healthReady ? "memo" : "health"}>
          {!healthReady
            ? "Preflight must pass before the CFO can issue a ruling."
            : started
              ? "Awaiting the CFO's board-ready ruling."
              : "Submit a decision — the CFO's ruling, risks, and conditions land here."}
        </EmptyState>
      )}
    </Panel>
  );
}

function MemoList({ title, items, dotTone }: { title: string; items: string[]; dotTone: "risk" | "info" }) {
  return (
    <div className="rounded-md border border-border bg-background p-2.5">
      <SectionLabel>{title}</SectionLabel>
      <ul className="mt-2 space-y-1.5">
        {items.map((item) => (
          <li key={item} className="flex gap-1.5 text-[12px] leading-relaxed text-muted-foreground">
            <span className={cx("mt-1.5 h-1 w-1 shrink-0 rounded-full", toneClasses(dotTone).dot)} />
            <span className="break-words">{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

// --------------------------------------------------------------------------- //
// Scenario impact — computed runway today vs after the decision.
// --------------------------------------------------------------------------- //
export function ScenarioImpactCard({ impact }: { impact?: RunwayImpact }) {
  const hasScenario = impact && typeof impact.scenario_runway_months === "number";
  const delta = impact?.delta_months ?? null;
  const deltaTone = delta == null ? "neutral" : delta < 0 ? "risk" : delta > 0 ? "positive" : "neutral";

  return (
    <Panel icon={delta != null && delta < 0 ? TrendingDown : TrendingUp} visualIcon="runway" title="Runway impact">
      {hasScenario ? (
        <>
          <div className="grid gap-2 [grid-template-columns:repeat(3,minmax(0,1fr))]">
            <ImpactTile label="Runway today" value={fmtMonths(impact?.current_runway_months)} />
            <ImpactTile label="After decision" value={fmtMonths(impact?.scenario_runway_months)} />
            <ImpactTile label="Net impact" value={fmtSignedMonths(delta)} tone={deltaTone} />
          </div>
          {impact?.note && <p className="mt-2.5 break-words text-[11px] leading-relaxed text-muted-foreground">{impact.note}</p>}
        </>
      ) : (
        <EmptyState visualIcon="runway">Runway delta is computed from the company cash record after the CFO rules.</EmptyState>
      )}
    </Panel>
  );
}

function ImpactTile({ label, value, tone }: { label: string; value: string; tone?: "risk" | "positive" | "neutral" }) {
  const cls = tone === "risk" ? "text-risk" : tone === "positive" ? "text-positive" : "text-foreground";
  return (
    <div className="rounded-md border border-border bg-background px-2 py-2 text-center">
      <div className="text-[10px] text-subtle-foreground">{label}</div>
      <div className={cx("mt-1 text-[18px] font-semibold leading-none tabular-nums", cls)}>{value}</div>
    </div>
  );
}
